# Generated by Django 2.1.4 on 2019-01-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_user', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=30)),
                ('user_cell', models.CharField(max_length=30)),
                ('id_number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('available', models.BooleanField(default=True)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=30)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='item',
            field=models.ForeignKey(on_delete=True, related_name='item_to_book', to='bookings.Item'),
        ),
    ]
