# Generated by Django 2.1.4 on 2019-01-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_pic',
            field=models.ImageField(default='pic_folder/None/no-img.png', upload_to='pic_folder/', verbose_name='itempic'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='display_pic',
            field=models.ImageField(default='pic_folder/None/no-img.png', upload_to='pic_folder/', verbose_name='foodpic'),
        ),
    ]
