# Generated by Django 2.1.4 on 2019-01-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190106_0613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_firstname',
            field=models.CharField(default='sssssssss', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user_lastname',
            field=models.CharField(default='ssddd', max_length=30),
            preserve_default=False,
        ),
    ]
