# Generated by Django 2.1.4 on 2019-01-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20190106_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
