# Generated by Django 2.1.4 on 2019-01-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_20190106_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_pic', models.ImageField(default='pic_folder/None/no-img.png', upload_to='pic_folder/', verbose_name='gallerypic')),
            ],
        ),
    ]
